name: .NET CI/CD Warrior

on:
  push:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    

jobs:
  build_warriors_exercise:
    runs-on: ubuntu-latest
    env:
      sln_path: ./Exercise.Warriors.sln
      dockerfile_path: ./src/Exercise.Warriors
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
        
    - name: Restore dependencies
      run: dotnet restore $sln_path
      
    - name: Build
      run: dotnet build $sln_path --no-restore
      
    - name: Test
      run: dotnet test $sln_path --no-build --verbosity n

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1      

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push Docker images
      id: docker_build
      uses: docker/build-push-action@v2.4.0
      with:
        tags: fjdominguez/warrior:${{ github.run_number }}
        context: ${{ env.dockerfile_path }}
        push: true

