name: .NET CI/CD Warrior

on:
  push:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    

jobs:
  build_warriors_exercise:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
        
    - name: Restore dependencies
      run: dotnet restore ./Exercise.Warriors.sln
      
    - name: Build
      run: dotnet build ./Exercise.Warriors.sln --no-restore
      
    - name: Test
      run: dotnet test ./Exercise.Warriors.sln --no-build --verbosity normal
