name: .NET CI/CD Warrior

on:
  push:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    

jobs:
  build_warriors_exercise:
    runs-on: ubuntu-latest
    env:
      sln_path: ./Exercise.Warriors.sln
      dockerfile_path: ./src/Exercise.Warriors
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
        
    - name: Restore dependencies
      run: dotnet restore $sln_path
      
    - name: Build
      run: dotnet build $sln_path --no-restore
      
    - name: Test
      run: dotnet test $sln_path --no-build --verbosity n

    - name: Build and push Docker images
      uses: docker/build-push-action@v2.4.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        tags: ${{ github.run_number }}
        path: .
        dockerfile: $dockerfile_path

